#  App Name
spring.application.name=book-inventory-management-frontend

# Server Port (IMPORTANT - backend se alag hona chahiye)
server.port=8081
#  Backend API Base URL ( VERY IMPORTANT)
backend.base-url=http://localhost:8080