package com.bookinventory.user.service;

import com.bookinventory.common.exception.BadRequestException;
import com.bookinventory.common.exception.ResourceNotFoundException;
import com.bookinventory.user.dto.PurchaseLogRequestDTO;
import com.bookinventory.user.dto.PurchaseLogResponseDTO;
import com.bookinventory.user.entity.PermRole;
import com.bookinventory.user.entity.PurchaseLog;
import com.bookinventory.user.entity.PurchaseLogId;
import com.bookinventory.user.entity.User;
import com.bookinventory.user.repository.PurchaseLogRepository;
import com.bookinventory.user.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class PurchaseLogServiceImplTest {

    // ─────────────────────────────────────────────────────────────
    // TWO mocks this time — the service depends on both
    // ─────────────────────────────────────────────────────────────
    @Mock
    private PurchaseLogRepository purchaseLogRepository;

    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private PurchaseLogServiceImpl purchaseLogService;

    // ─────────────────────────────────────────────────────────────
    // Test data — built fresh before every test via @BeforeEach
    // ─────────────────────────────────────────────────────────────
    private User        sampleUser;
    private PermRole    registeredUserRole;
    private PurchaseLog purchaseLog1;
    private PurchaseLog purchaseLog2;

    @BeforeEach
    void setUp() {

        // Build a role
        registeredUserRole = new PermRole(2, "RegisteredUser");

        // Build a sample user
        // We do NOT use the DB — this is just a plain Java object
        sampleUser = new User(
                "Doe",          // lastName
                "John",         // firstName
                "(123) 456-7890", // phoneNumber
                "johndoe",      // userName
                "pass123",      // password
                registeredUserRole
        );
        sampleUser.setUserId(1); // manually set ID (normally auto-generated by DB)

        // Build two purchase logs for user 1
        // PurchaseLogId is the composite key → (userId=1, inventoryId=101)
        PurchaseLogId id1 = new PurchaseLogId(1, 101);
        purchaseLog1 = new PurchaseLog(id1, sampleUser);

        PurchaseLogId id2 = new PurchaseLogId(1, 202);
        purchaseLog2 = new PurchaseLog(id2, sampleUser);
    }

    // ═════════════════════════════════════════════════════════════
    // Tests for: addPurchase()
    // ═════════════════════════════════════════════════════════════

    @Test
    @DisplayName("addPurchase() → successfully saves a new purchase")
    void addPurchase_WhenValid_ShouldSaveAndReturnDTO() {

        // ── ARRANGE ───────────────────────────────────────────
        // Step 1: Build the incoming request DTO
        PurchaseLogRequestDTO requestDTO = new PurchaseLogRequestDTO(1, 101);

        // Step 2: Mock — user EXISTS in DB
        when(userRepository.findById(1))
                .thenReturn(Optional.of(sampleUser));

        // Step 3: Mock — this purchase does NOT already exist (not a duplicate)
        when(purchaseLogRepository
                .existsById_UserIdAndId_InventoryId(1, 101))
                .thenReturn(false);

        // Step 4: Mock — when save() is called, return our pre-built purchaseLog1
        // any(PurchaseLog.class) means:
        //   "I don't care WHAT PurchaseLog object is passed in — just return this"
        when(purchaseLogRepository.save(any(PurchaseLog.class)))
                .thenReturn(purchaseLog1);

        // ── ACT ───────────────────────────────────────────────
        PurchaseLogResponseDTO result = purchaseLogService.addPurchase(requestDTO);

        // ── ASSERT ────────────────────────────────────────────
        // Result should not be null
        assertThat(result).isNotNull();

        // IDs should match what we saved
        assertThat(result.getUserId()).isEqualTo(1);
        assertThat(result.getInventoryId()).isEqualTo(101);

        // User details should be populated from the User entity
        assertThat(result.getUserFirstName()).isEqualTo("John");
        assertThat(result.getUserLastName()).isEqualTo("Doe");
        assertThat(result.getUserName()).isEqualTo("johndoe");

        // Verify the flow happened in the right order:
        // 1. It looked up the user
        verify(userRepository, times(1)).findById(1);
        // 2. It checked for duplicate
        verify(purchaseLogRepository, times(1))
                .existsById_UserIdAndId_InventoryId(1, 101);
        // 3. It actually saved
        verify(purchaseLogRepository, times(1)).save(any(PurchaseLog.class));
    }

    @Test
    @DisplayName("addPurchase() → throws ResourceNotFoundException when user not found")
    void addPurchase_WhenUserNotFound_ShouldThrowException() {

        // ── ARRANGE ───────────────────────────────────────────
        PurchaseLogRequestDTO requestDTO = new PurchaseLogRequestDTO(99, 101);

        // User does NOT exist in DB
        when(userRepository.findById(99))
                .thenReturn(Optional.empty());

        // ── ASSERT + ACT ──────────────────────────────────────
        assertThatThrownBy(() -> purchaseLogService.addPurchase(requestDTO))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessageContaining("99");

        // IMPORTANT: if user not found, we should NEVER reach save()
        // verify(mock, never()) checks that a method was NEVER called
        verify(purchaseLogRepository, never()).save(any());
    }

    @Test
    @DisplayName("addPurchase() → throws BadRequestException when purchase already exists")
    void addPurchase_WhenDuplicatePurchase_ShouldThrowException() {

        // ── ARRANGE ───────────────────────────────────────────
        PurchaseLogRequestDTO requestDTO = new PurchaseLogRequestDTO(1, 101);

        // User EXISTS
        when(userRepository.findById(1))
                .thenReturn(Optional.of(sampleUser));

        // This purchase ALREADY EXISTS → duplicate!
        when(purchaseLogRepository
                .existsById_UserIdAndId_InventoryId(1, 101))
                .thenReturn(true);

        // ── ASSERT + ACT ──────────────────────────────────────
        assertThatThrownBy(() -> purchaseLogService.addPurchase(requestDTO))
                .isInstanceOf(BadRequestException.class)
                .hasMessageContaining("already purchased");

        // save() should NEVER be called when it's a duplicate
        verify(purchaseLogRepository, never()).save(any());
    }

    @Test
    @DisplayName("addPurchase() → saves PurchaseLog with correct composite key")
    void addPurchase_ShouldSaveWithCorrectCompositeKey() {

        // ── ARRANGE ───────────────────────────────────────────
        PurchaseLogRequestDTO requestDTO = new PurchaseLogRequestDTO(1, 303);

        when(userRepository.findById(1))
                .thenReturn(Optional.of(sampleUser));

        when(purchaseLogRepository
                .existsById_UserIdAndId_InventoryId(1, 303))
                .thenReturn(false);

        // ─────────────────────────────────────────────────────
        // ArgumentCaptor — this is a powerful Mockito tool
        //
        // Instead of just saying "save() was called with something",
        // we CAPTURE the actual PurchaseLog object that was passed
        // so we can inspect its fields
        // ─────────────────────────────────────────────────────
        ArgumentCaptor<PurchaseLog> captor =
                ArgumentCaptor.forClass(PurchaseLog.class);

        PurchaseLogId savedId = new PurchaseLogId(1, 303);
        PurchaseLog   savedLog = new PurchaseLog(savedId, sampleUser);

        when(purchaseLogRepository.save(any(PurchaseLog.class)))
                .thenReturn(savedLog);

        // ── ACT ───────────────────────────────────────────────
        purchaseLogService.addPurchase(requestDTO);

        // ── ASSERT ────────────────────────────────────────────
        // Capture the PurchaseLog that was passed to save()
        verify(purchaseLogRepository).save(captor.capture());

        PurchaseLog captured = captor.getValue();

        // Check the composite key was built correctly
        assertThat(captured.getId().getUserId()).isEqualTo(1);
        assertThat(captured.getId().getInventoryId()).isEqualTo(303);

        // Check the user was attached
        assertThat(captured.getUser().getUserId()).isEqualTo(1);
    }

    // ═════════════════════════════════════════════════════════════
    // Tests for: getPurchasesByUser()
    // ═════════════════════════════════════════════════════════════

    @Test
    @DisplayName("getPurchasesByUser() → returns purchases when user exists")
    void getPurchasesByUser_WhenUserExists_ShouldReturnList() {

        // ── ARRANGE ───────────────────────────────────────────
        // User exists check returns true
        when(userRepository.existsById(1)).thenReturn(true);

        // Repository returns 2 purchase logs
        when(purchaseLogRepository.findPurchasesByUserId(1))
                .thenReturn(Arrays.asList(purchaseLog1, purchaseLog2));

        // ── ACT ───────────────────────────────────────────────
        List<PurchaseLogResponseDTO> result =
                purchaseLogService.getPurchasesByUser(1);

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).hasSize(2);

        // First purchase
        assertThat(result.get(0).getUserId()).isEqualTo(1);
        assertThat(result.get(0).getInventoryId()).isEqualTo(101);
        assertThat(result.get(0).getUserName()).isEqualTo("johndoe");

        // Second purchase
        assertThat(result.get(1).getUserId()).isEqualTo(1);
        assertThat(result.get(1).getInventoryId()).isEqualTo(202);

        verify(userRepository, times(1)).existsById(1);
        verify(purchaseLogRepository, times(1)).findPurchasesByUserId(1);
    }

    @Test
    @DisplayName("getPurchasesByUser() → throws exception when user not found")
    void getPurchasesByUser_WhenUserNotFound_ShouldThrowException() {

        // ── ARRANGE ───────────────────────────────────────────
        when(userRepository.existsById(99)).thenReturn(false);

        // ── ASSERT + ACT ──────────────────────────────────────
        assertThatThrownBy(() -> purchaseLogService.getPurchasesByUser(99))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessageContaining("99");

        // If user not found, never query purchases
        verify(purchaseLogRepository, never()).findPurchasesByUserId(any());
    }

    @Test
    @DisplayName("getPurchasesByUser() → returns empty list when user has no purchases")
    void getPurchasesByUser_WhenNoPurchases_ShouldReturnEmptyList() {

        // ── ARRANGE ───────────────────────────────────────────
        when(userRepository.existsById(1)).thenReturn(true);

        // Empty list — user exists but bought nothing
        when(purchaseLogRepository.findPurchasesByUserId(1))
                .thenReturn(Collections.emptyList());

        // ── ACT ───────────────────────────────────────────────
        List<PurchaseLogResponseDTO> result =
                purchaseLogService.getPurchasesByUser(1);

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).isEmpty();
    }

    // ═════════════════════════════════════════════════════════════
    // Tests for: getInventoryIdsByUser()
    // ═════════════════════════════════════════════════════════════

    @Test
    @DisplayName("getInventoryIdsByUser() → returns inventory IDs when user exists")
    void getInventoryIdsByUser_WhenUserExists_ShouldReturnIds() {

        // ── ARRANGE ───────────────────────────────────────────
        when(userRepository.existsById(1)).thenReturn(true);

        when(purchaseLogRepository.findInventoryIdsByUserId(1))
                .thenReturn(Arrays.asList(101, 202, 303));

        // ── ACT ───────────────────────────────────────────────
        List<Integer> result = purchaseLogService.getInventoryIdsByUser(1);

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).hasSize(3);
        assertThat(result).containsExactly(101, 202, 303);

        verify(userRepository, times(1)).existsById(1);
        verify(purchaseLogRepository, times(1)).findInventoryIdsByUserId(1);
    }

    @Test
    @DisplayName("getInventoryIdsByUser() → throws exception when user not found")
    void getInventoryIdsByUser_WhenUserNotFound_ShouldThrowException() {

        // ── ARRANGE ───────────────────────────────────────────
        when(userRepository.existsById(55)).thenReturn(false);

        // ── ASSERT + ACT ──────────────────────────────────────
        assertThatThrownBy(() -> purchaseLogService.getInventoryIdsByUser(55))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessageContaining("55");

        verify(purchaseLogRepository, never()).findInventoryIdsByUserId(any());
    }

    // ═════════════════════════════════════════════════════════════
    // Tests for: hasPurchased()
    // ═════════════════════════════════════════════════════════════

    @Test
    @DisplayName("hasPurchased() → returns true when purchase exists")
    void hasPurchased_WhenPurchaseExists_ShouldReturnTrue() {

        // ── ARRANGE ───────────────────────────────────────────
        when(purchaseLogRepository
                .existsById_UserIdAndId_InventoryId(1, 101))
                .thenReturn(true);

        // ── ACT ───────────────────────────────────────────────
        boolean result = purchaseLogService.hasPurchased(1, 101);

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).isTrue();

        verify(purchaseLogRepository, times(1))
                .existsById_UserIdAndId_InventoryId(1, 101);
    }

    @Test
    @DisplayName("hasPurchased() → returns false when purchase does not exist")
    void hasPurchased_WhenPurchaseNotExists_ShouldReturnFalse() {

        // ── ARRANGE ───────────────────────────────────────────
        when(purchaseLogRepository
                .existsById_UserIdAndId_InventoryId(1, 999))
                .thenReturn(false);

        // ── ACT ───────────────────────────────────────────────
        boolean result = purchaseLogService.hasPurchased(1, 999);

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).isFalse();
    }

    // ═════════════════════════════════════════════════════════════
    // Tests for: getPurchaseCount()
    // ═════════════════════════════════════════════════════════════

    @Test
    @DisplayName("getPurchaseCount() → returns correct count when user exists")
    void getPurchaseCount_WhenUserExists_ShouldReturnCount() {

        // ── ARRANGE ───────────────────────────────────────────
        when(userRepository.existsById(1)).thenReturn(true);
        when(purchaseLogRepository.countById_UserId(1)).thenReturn(5L);

        // ── ACT ───────────────────────────────────────────────
        long result = purchaseLogService.getPurchaseCount(1);

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).isEqualTo(5L);

        verify(userRepository, times(1)).existsById(1);
        verify(purchaseLogRepository, times(1)).countById_UserId(1);
    }

    @Test
    @DisplayName("getPurchaseCount() → returns 0 when user has no purchases")
    void getPurchaseCount_WhenNoPurchases_ShouldReturnZero() {

        // ── ARRANGE ───────────────────────────────────────────
        when(userRepository.existsById(1)).thenReturn(true);
        when(purchaseLogRepository.countById_UserId(1)).thenReturn(0L);

        // ── ACT ───────────────────────────────────────────────
        long result = purchaseLogService.getPurchaseCount(1);

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).isZero();
    }

    @Test
    @DisplayName("getPurchaseCount() → throws exception when user not found")
    void getPurchaseCount_WhenUserNotFound_ShouldThrowException() {

        // ── ARRANGE ───────────────────────────────────────────
        when(userRepository.existsById(77)).thenReturn(false);

        // ── ASSERT + ACT ──────────────────────────────────────
        assertThatThrownBy(() -> purchaseLogService.getPurchaseCount(77))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessageContaining("77");

        verify(purchaseLogRepository, never()).countById_UserId(any());
    }

    // ═════════════════════════════════════════════════════════════
    // Tests for: getPurchasesByInventory()
    // ═════════════════════════════════════════════════════════════

    @Test
    @DisplayName("getPurchasesByInventory() → returns all purchases for an inventory item")
    void getPurchasesByInventory_ShouldReturnPurchases() {

        // ── ARRANGE ───────────────────────────────────────────
        // Two different users bought inventory item 101
        User anotherUser = new User(
                "Smith", "Jane",
                "(987) 654-3210",
                "janesmith", "pass456",
                registeredUserRole
        );
        anotherUser.setUserId(2);

        PurchaseLog log2 = new PurchaseLog(new PurchaseLogId(2, 101), anotherUser);

        when(purchaseLogRepository.findById_InventoryId(101))
                .thenReturn(Arrays.asList(purchaseLog1, log2));

        // ── ACT ───────────────────────────────────────────────
        List<PurchaseLogResponseDTO> result =
                purchaseLogService.getPurchasesByInventory(101);

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).hasSize(2);

        // First buyer: John Doe
        assertThat(result.get(0).getUserId()).isEqualTo(1);
        assertThat(result.get(0).getUserName()).isEqualTo("johndoe");

        // Second buyer: Jane Smith
        assertThat(result.get(1).getUserId()).isEqualTo(2);
        assertThat(result.get(1).getUserName()).isEqualTo("janesmith");

        verify(purchaseLogRepository, times(1)).findById_InventoryId(101);
    }

    @Test
    @DisplayName("getPurchasesByInventory() → returns empty list when no one bought the item")
    void getPurchasesByInventory_WhenNoPurchases_ShouldReturnEmptyList() {

        // ── ARRANGE ───────────────────────────────────────────
        when(purchaseLogRepository.findById_InventoryId(999))
                .thenReturn(Collections.emptyList());

        // ── ACT ───────────────────────────────────────────────
        List<PurchaseLogResponseDTO> result =
                purchaseLogService.getPurchasesByInventory(999);

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).isEmpty();
    }

    // ═════════════════════════════════════════════════════════════
    // Tests for: getAllPurchases()
    // ═════════════════════════════════════════════════════════════

    @Test
    @DisplayName("getAllPurchases() → returns all purchases in the system")
    void getAllPurchases_ShouldReturnAllPurchases() {

        // ── ARRANGE ───────────────────────────────────────────
        when(purchaseLogRepository.findAll())
                .thenReturn(Arrays.asList(purchaseLog1, purchaseLog2));

        // ── ACT ───────────────────────────────────────────────
        List<PurchaseLogResponseDTO> result =
                purchaseLogService.getAllPurchases();

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).hasSize(2);

        assertThat(result.get(0).getInventoryId()).isEqualTo(101);
        assertThat(result.get(1).getInventoryId()).isEqualTo(202);

        verify(purchaseLogRepository, times(1)).findAll();
    }

    @Test
    @DisplayName("getAllPurchases() → returns empty list when system has no purchases")
    void getAllPurchases_WhenNoPurchases_ShouldReturnEmptyList() {

        // ── ARRANGE ───────────────────────────────────────────
        when(purchaseLogRepository.findAll())
                .thenReturn(Collections.emptyList());

        // ── ACT ───────────────────────────────────────────────
        List<PurchaseLogResponseDTO> result =
                purchaseLogService.getAllPurchases();

        // ── ASSERT ────────────────────────────────────────────
        assertThat(result).isEmpty();
    }
}